function create(x, y, width, height)
    entity = getNewEntity("baseLuaEntity")
    sizeMultiplier = getGlobalValue("sizeMultiplier")
    setEntityX(entity, x * sizeMultiplier) 
    setEntityY(entity, y * sizeMultiplier)
    addEntityValue(entity, "orientation", "bool")
    setEntityValue(entity, "orientation", true)
    startEntityAnimation(entity, "electricFieldUp")
    setEntityRenderWidth(entity, width * sizeMultiplier)
    setEntityRenderHeight(entity, height * sizeMultiplier)
    addEntityCollisionBox(entity, 0, 0, width * sizeMultiplier, height * sizeMultiplier)
    addEntityToGroup(entity, "ElectricFields")
    addEntityToRenderGroup(entity, "550ElectricFields")
    return entity
end
